[build]
target = "riscv32imc-unknown-none-elf"

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,-Tlink.x",
  "-C", "force-frame-pointers=yes",
]

[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]

[env]
ESP_IDF_VERSION = "v5.3.2"
MCU = "esp32c3"
ESP_IDF_SDKCONFIG_DEFAULTS = "./sdkconfig.defaults"
ESP_IDF_TOOLS_INSTALL_DIR = "~/.espressif"
RUST_ESP32_STD_HELLO_GPIO = "2"
