[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[build]
target = "riscv32imc-unknown-none-elf"

[env]
ESP_IDF_VERSION = "v5.3.2"
MCU = "esp32c3"
ESP_IDF_SDKCONFIG_DEFAULTS = "./sdkconfig.defaults"
